# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-09 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=1024)),
                ('type', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('note', models.CharField(max_length=512)),
            ],
        ),
        migrations.AddField(
            model_name='column',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Domain'),
        ),
        migrations.AddField(
            model_name='column',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Survey'),
        ),
    ]
