# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AltraSede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOperativa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='AreaOperativaAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_operativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.AreaOperativa')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOperativaFuturo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_operativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.AreaOperativa')),
            ],
        ),
        migrations.CreateModel(
            name='AreaOperativaPregresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_operativa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.AreaOperativa')),
            ],
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, null=True)),
                ('nome_referente', models.CharField(max_length=512, null=True)),
                ('note', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Benefit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='BenefitFuturo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('benefit', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Benefit')),
            ],
        ),
        migrations.CreateModel(
            name='CampoStudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CampoStudiAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_studi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.CampoStudi')),
            ],
        ),
        migrations.CreateModel(
            name='Citta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Column',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='', max_length=256)),
                ('type', models.CharField(default='', max_length=256)),
                ('required', models.BooleanField(default=True)),
                ('option', models.CharField(default='', max_length=2048)),
                ('description', models.CharField(default='', max_length=2048)),
                ('jsonCode', models.CharField(default='', max_length=4096)),
                ('num_order', models.IntegerField()),
                ('cid', models.CharField(default='', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ConoscenzaSpecifica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='ConoscenzaSpecificaAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conoscenza_specifica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.ConoscenzaSpecifica')),
            ],
        ),
        migrations.CreateModel(
            name='Esame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EsameAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Esame')),
            ],
        ),
        migrations.CreateModel(
            name='GradoStudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Interesse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='InteresseFuturo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interesse', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Interesse')),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_user', models.CharField(default='anonymous', max_length=256)),
                ('type_user', models.CharField(default='people', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Lavoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_referente', models.CharField(max_length=64, null=True)),
                ('note_lavoro', models.CharField(max_length=512, null=True)),
                ('durata_lavoro', models.IntegerField(null=True)),
                ('distanza_massima', models.CharField(max_length=64, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Azienda')),
            ],
        ),
        migrations.CreateModel(
            name='Lingua',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LinguaAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lingua', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Lingua')),
            ],
        ),
        migrations.CreateModel(
            name='LivelloCariera',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='LivelloCarieraAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello_cariera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.LivelloCariera')),
            ],
        ),
        migrations.CreateModel(
            name='LivelloCarieraFuturo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello_cariera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.LivelloCariera')),
            ],
        ),
        migrations.CreateModel(
            name='LivelloCarieraPregresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('livello_cariera', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.LivelloCariera')),
            ],
        ),
        migrations.CreateModel(
            name='LivelloPC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Mansione',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='MansioneAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mansione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Mansione')),
            ],
        ),
        migrations.CreateModel(
            name='MansioneFuturo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mansione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Mansione')),
            ],
        ),
        migrations.CreateModel(
            name='MansionePregresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mansione', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Mansione')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, null=True)),
                ('cap', models.CharField(max_length=64, null=True)),
                ('citta', models.CharField(max_length=64, null=True)),
                ('anno_nascita', models.IntegerField(null=True)),
                ('note', models.CharField(max_length=512, null=True)),
                ('voto_finale', models.IntegerField(null=True)),
                ('esperienze_pregresse', models.BooleanField(default=False)),
                ('desc_esperienze_pregresse', models.CharField(max_length=512, null=True)),
                ('numero_attivita_svolte', models.IntegerField(default=0, null=True)),
                ('numero_mesi_attivita_svolte', models.IntegerField(default=0, null=True)),
                ('possibilita_trasferirsi', models.BooleanField(default=False)),
                ('stipendio_futuro', models.IntegerField(default=0, null=True)),
                ('grado_studi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.GradoStudi')),
                ('livello_uso_computer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.LivelloPC')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(default='', max_length=256)),
                ('type_value', models.CharField(default='single', max_length=256)),
                ('column', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Column')),
                ('interview', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Interview')),
            ],
        ),
        migrations.CreateModel(
            name='Ruolo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='RuoloAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona')),
                ('ruolo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Ruolo')),
            ],
        ),
        migrations.CreateModel(
            name='RuoloFuturo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona')),
                ('ruolo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Ruolo')),
            ],
        ),
        migrations.CreateModel(
            name='RuoloPregresso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona')),
                ('ruolo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Ruolo')),
            ],
        ),
        migrations.CreateModel(
            name='Stato',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='StatoAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona')),
                ('stato', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Stato')),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('note', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContratto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrattoAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona')),
                ('tipo_contratto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.TipoContratto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrattoFuturo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona')),
                ('tipo_contratto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.TipoContratto')),
            ],
        ),
        migrations.CreateModel(
            name='TipoContrattoPregesso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona')),
                ('tipo_contratto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.TipoContratto')),
            ],
        ),
        migrations.CreateModel(
            name='Zona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='persona',
            name='zona',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Zona'),
        ),
        migrations.AddField(
            model_name='mansionepregresso',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='mansionefuturo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='mansioneattuale',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='livellocarierapregresso',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='livellocarierafuturo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='livellocarieraattuale',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='linguaattuale',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='interessefuturo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='esameattuale',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='conoscenzaspecificaattuale',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='column',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Survey'),
        ),
        migrations.AddField(
            model_name='campostudiattuale',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='benefitfuturo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='azienda',
            name='citta_sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Citta'),
        ),
        migrations.AddField(
            model_name='areaoperativapregresso',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='areaoperativafuturo',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='areaoperativaattuale',
            name='persona',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona'),
        ),
        migrations.AddField(
            model_name='altrasede',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Azienda'),
        ),
        migrations.AddField(
            model_name='altrasede',
            name='citta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Citta'),
        ),
    ]
