# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-15 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='num_order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
