# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 16:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0003_auto_20160316_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='survey',
            name='pub_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
