# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-16 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0004_auto_20160316_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='column',
            name='cid',
            field=models.CharField(default='', max_length=32),
        ),
    ]
