# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-17 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0005_column_cid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='required',
            field=models.CharField(default='true', max_length=8),
        ),
    ]
