# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-03-17 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0006_auto_20160317_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='column',
            name='required',
            field=models.BooleanField(default=True),
        ),
    ]
