# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 10:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0009_auto_20160406_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='desc_esperienze_pregresse',
            field=models.CharField(max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='esperienze_pregresse',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_attivita_svolte',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_mesi_attivita_svolte',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='persona',
            name='possibilita_trasferirsi',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='persona',
            name='stipendio_futuro',
            field=models.IntegerField(default=0),
        ),
    ]
