# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0010_auto_20160406_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='numero_attivita_svolte',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='numero_mesi_attivita_svolte',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='persona',
            name='stipendio_futuro',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
