# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0012_auto_20160406_1528'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ruoloattuale',
            old_name='Persona',
            new_name='persona',
        ),
    ]
