# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 13:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0013_auto_20160406_1537'),
    ]

    operations = [
        migrations.CreateModel(
            name='Esame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='EsameAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esame', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Esame')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona')),
            ],
        ),
    ]
