# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 15:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0014_esame_esameattuale'),
    ]

    operations = [
        migrations.CreateModel(
            name='AltraSede',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Azienda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=64, null=True)),
                ('nome_referente', models.CharField(max_length=512, null=True)),
                ('note', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Citta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.AddField(
            model_name='azienda',
            name='citta_sede',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Citta'),
        ),
        migrations.AddField(
            model_name='altrasede',
            name='azienda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Azienda'),
        ),
        migrations.AddField(
            model_name='altrasede',
            name='citta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Citta'),
        ),
    ]
