# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-04-06 16:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('createSurvey', '0015_auto_20160406_1722'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoStudi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valore', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='CampoStudiAttuale',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_studi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='createSurvey.CampoStudi')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Persona')),
            ],
        ),
        migrations.CreateModel(
            name='Lavoro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_referente', models.CharField(max_length=64, null=True)),
                ('note_lavoro', models.CharField(max_length=512, null=True)),
                ('durata_lavoro', models.IntegerField(null=True)),
                ('distanza_massima', models.CharField(max_length=64, null=True)),
                ('azienda', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='createSurvey.Azienda')),
            ],
        ),
    ]
